input_folder_path = '/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2019-09-06/build-brain-output/full-as-named-tree-mats' ;
output_folder_path = '/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2019-09-06/build-brain-output/frags-small-chunk' ;
maximum_core_count_desired = inf ;
minimum_centerpoint_count_per_fragment = 2 ;    
bounding_box_low_corner_xyz = [72882 16245 36940] ;
bounding_box_high_corner_xyz = [74040 17380 37630] ;

workflow1_frags_as_swcs(input_folder_path, ...
                        output_folder_path, ...
                        maximum_core_count_desired, ...
                        minimum_centerpoint_count_per_fragment, ...
                        bounding_box_low_corner_xyz, ...
                        bounding_box_high_corner_xyz) ;                            
