input_folder_path = '/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2018-08-01/prob0_swcs_redone/full-as-mats' ;
output_folder_path = '/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2018-08-01/prob0_swcs_redone/frags' ;
maximum_core_count_desired = inf ;
minimum_centerpoint_count_per_fragment = 1 ;    
bounding_box_low_corner_xyz = [-inf -inf -inf] ;
bounding_box_high_corner_xyz = [+inf +inf +inf] ;

workflow1_frags_as_swcs(input_folder_path, ...
                        output_folder_path, ...
                        maximum_core_count_desired, ...
                        minimum_centerpoint_count_per_fragment, ...
                        bounding_box_low_corner_xyz, ...
                        bounding_box_high_corner_xyz) ;                            
