input_folder_path = '/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2019-09-06/build-brain-output/full-as-named-tree-mats' ;
output_folder_path = '/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2019-09-06/build-brain-output/frags' ;
maximum_core_count_desired = inf ;
minimum_centerpoint_count_per_fragment = 2 ;    
bounding_box_low_corner_xyz = [-inf -inf -inf] ;
bounding_box_high_corner_xyz = [+inf +inf +inf] ;

workflow1_frags_as_swcs(input_folder_path, ...
                        output_folder_path, ...
                        maximum_core_count_desired, ...
                        minimum_centerpoint_count_per_fragment, ...
                        bounding_box_low_corner_xyz, ...
                        bounding_box_high_corner_xyz) ;                            
