function is_tree_near_some_query_tree_from_tree_id = ...
        find_trees_near_query_trees(...
            query_forest_as_named_trees, ...
            pool_kd_tree, ...
            pool_node_count, ...
            tree_id_from_pool_node_id, ...
            pool_tree_count, ...
            blast_radius_in_um)
        
    query_count = length(query_forest_as_named_trees) ;
    is_tree_near_some_query_tree_from_tree_id = false(pool_tree_count, 1) ;
    for i = 1:query_count ,
        query_as_named_tree = query_forest_as_named_trees(i) ;
        is_tree_near_query_tree_from_tree_id = ...
            find_trees_near_query_tree(...
                query_as_named_tree, ...
                pool_kd_tree, ...
                pool_node_count, ...
                tree_id_from_pool_node_id, ...
                pool_tree_count, ...
                blast_radius_in_um) ;
        is_tree_near_some_query_tree_from_tree_id = is_tree_near_some_query_tree_from_tree_id | is_tree_near_query_tree_from_tree_id ;    
    end
end
