sample_date = '2018-10-01-will-p-map-settings-2' ;
input_folder_path = ...
    sprintf('/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/%s/build-brain-output/full-as-named-tree-mats', ...
            sample_date) ;
output_folder_path = ...
    sprintf('/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/%s/build-brain-output/frags-with-5-or-more-nodes-as-mats', ...
            sample_date) ;       
maximum_core_count_desired = inf ;
minimum_centerpoint_count_per_fragment = 5 ;    
bounding_box_low_corner_xyz = [-inf -inf -inf] ;
bounding_box_high_corner_xyz = [+inf +inf +inf] ;

generate_fragments(input_folder_path, ...
                   output_folder_path, ...
                   'mat', ...
                   maximum_core_count_desired, ...
                   minimum_centerpoint_count_per_fragment, ...
                   bounding_box_low_corner_xyz, ...
                   bounding_box_high_corner_xyz) ;
