function write_fragments_as_swcs(fragment_output_folder_path, component_id, outtree, params)
    XYZ = [outtree.X,outtree.Y,outtree.Z]-1 ; % -1 one is heuristic/bug
    R = outtree.R ;
    D = outtree.D ;
    [L,~] = getBranches(outtree.dA) ;
    fragment_count = length(L) ;
    
    % Generate colormap
    raw_color_from_fragment_id = jet(fragment_count);
    color_from_fragment_id = raw_color_from_fragment_id(randperm(fragment_count),:) ;
    
    % Write each fragment to disk as a .swc file
    for fragment_id = 1:fragment_count ,
        L_this_fragment = L(fragment_id) ;
        out = L_this_fragment.set ;
        if isempty(out)
            continue
        end        
        
        % .swc file name
        fragment_swc_file_name = sprintf('auto-cc-%04d-branch-%04d.swc', component_id, fragment_id) ;
        fragment_swc_file_path = fullfile(fragment_output_folder_path, fragment_swc_file_name);

        % If the output file already exists, skip it
        if exist(fragment_swc_file_path, 'file') ,
            continue ;
        end
        
        XYZout = XYZ(out,:);
        Rout = R(out);
        Dout = D(out);

        % transform location
        XYZout = pix2um(params, XYZout) ; % center anisotropy to compansate imresize
        nout = size(XYZout,1) ;
        swcData = [(1:nout)' Dout XYZout Rout (0:nout-1)'] ;
        swcData(1,7) = -1;
        offset = mean(swcData(:,3:5), 1) ;        

        swcData(:,3:5) = swcData(:,3:5)-ones(size(swcData,1),1)*offset;
        % write swc
        fid = fopen(fragment_swc_file_path,'w');
        mytxt = sprintf('# Generated by pw skel algorithm\n');
        fprintf(fid,'%s',mytxt);
        mytxt = sprintf('# OFFSET %.6f %.6f %.6f\n',offset);
        fprintf(fid,'%s',mytxt);
        mytxt = sprintf('# COLOR %f,%f,%f\n',color_from_fragment_id(fragment_id,1),color_from_fragment_id(fragment_id,2),color_from_fragment_id(fragment_id,3));
        fprintf(fid,'%s',mytxt);
        mytxt = sprintf('# NAME %s\n',fragment_swc_file_name);
        fprintf(fid,'%s',mytxt);
        fprintf(fid,'%d %d %f %f %f %d %d\n',swcData');
        fclose(fid);
    end
end
