function write_full_tree_as_swc(full_trees_output_folder_path, component_id, outtree, params, color_from_component_id)
    Aout = outtree.dA;
    nout = size(Aout,1);
    XYZout = [outtree.X,outtree.Y,outtree.Z]-1;
    Rout = outtree.R;
    Dout = outtree.D;
    % transform location
    XYZout = pix2um(params,XYZout); % center anisotropy to compansate imresize
    %

    At = Aout+Aout';
    [DISC,~,~] = graphtraverse(At,1,'Method','DFS');
    At(1:end,:) = At(DISC,:);
    At(:,1:end) = At(:,DISC);
    XYZout = XYZout(DISC,:);
    Rout = Rout(DISC,:);
    Dout = Dout(DISC,:);
    %%
%     if strcmp(version('-release'),'2015b')
%         [dist,pred] = graphalgs(algorithmkeys{algorithm},debug_level,directed,At,1);
%     else
    [~,~,pred] = graphshortestpath(At,1,'DIRECTED',false);
%     end
    swcData = [(1:nout)' Dout XYZout Rout pred(:)];
    swcData(1,7) = -1;
    offset = min(swcData(:,3:5),[],1);
    swcData(:,3:5) = swcData(:,3:5)-ones(size(swcData,1),1)*offset;
    
    
    tree_swc_file_name = sprintf('auto_cc-%04d.swc',component_id);
    tree_swc_file_path = fullfile(full_trees_output_folder_path, tree_swc_file_name);
    % write swc
    fid = fopen(tree_swc_file_path,'w');
    mytxt = sprintf('# Generated by pw skel algorithm\n');
    fprintf(fid,'%s',mytxt);
    mytxt = sprintf('# OFFSET %.6f %.6f %.6f\n',offset);
    fprintf(fid,'%s',mytxt);
    mytxt = sprintf('# COLOR %f,%f,%f\n', ...
                    color_from_component_id(component_id,1), ...
                    color_from_component_id(component_id,2), ...
                    color_from_component_id(component_id,3)) ;
    fprintf(fid,'%s',mytxt);
    mytxt = sprintf('# NAME %s\n',tree_swc_file_name);
    fprintf(fid,'%s',mytxt);
    fprintf(fid,'%d %d %f %f %f %d %d\n',swcData');
    fclose(fid);
end
