function write_full_tree_in_um_as_swc(tree_swc_file_name, color, tree_as_struct)
    Aout = tree_as_struct.dA;
    nout = size(Aout,1);
    %XYZout = [outtree.X,outtree.Y,outtree.Z]-1;  % this is what
    %caused the horrble off-by-one issues in August 2019!
    XYZout = [tree_as_struct.X,tree_as_struct.Y,tree_as_struct.Z] ;  % must be in um
    Rout = tree_as_struct.R;
    Dout = tree_as_struct.D;
    % transform location
    %XYZout = pix2um(params,XYZout); % center anisotropy to compansate imresize
    %

    At = Aout+Aout';
    [DISC,~,~] = graphtraverse(At,1,'Method','DFS');
    At(1:end,:) = At(DISC,:);
    At(:,1:end) = At(:,DISC);
    XYZout = XYZout(DISC,:);
    Rout = Rout(DISC,:);
    Dout = Dout(DISC,:);
    %%
%     if strcmp(version('-release'),'2015b')
%         [dist,pred] = graphalgs(algorithmkeys{algorithm},debug_level,directed,At,1);
%     else
    [~,~,pred] = graphshortestpath(At,1,'DIRECTED',false);
%     end
    swcData = [(1:nout)' Dout XYZout Rout pred(:)];
    swcData(1,7) = -1;
    offset = min(swcData(:,3:5),[],1);
    swcData(:,3:5) = swcData(:,3:5)-ones(size(swcData,1),1)*offset;
    
    
    %tree_swc_file_name = sprintf('auto_cc-%04d.swc',component_id);
    %tree_swc_file_path = fullfile(full_trees_output_folder_path, tree_swc_file_name);
    % write swc
    fid = fopen(tree_swc_file_name,'w');
    mytxt = sprintf('# Generated by pw skel algorithm\n');
    fprintf(fid,'%s',mytxt);
    mytxt = sprintf('# OFFSET %.6f %.6f %.6f\n',offset);
    fprintf(fid,'%s',mytxt);
    mytxt = sprintf('# COLOR %f,%f,%f\n', ...
                    color(1), ...
                    color(2), ...
                    color(3)) ;
    fprintf(fid,'%s',mytxt);
    mytxt = sprintf('# NAME %s\n',tree_swc_file_name);
    fprintf(fid,'%s',mytxt);
    fprintf(fid,'%d %d %f %f %f %d %d\n',swcData');
    fclose(fid);
end
